/** TgFox Blue Console: real referral and official support workspace. */
import { useEffect, useState } from "react";
import { Copy, Headphones, LoaderCircle, Share2, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { type Referral, type Support, tgfoxApi } from "@/lib/api";
import { openTelegramLink } from "@/lib/tg";

const money = (amount: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2 }).format(amount || 0);

export function CommunityWorkspace() {
  const [referral, setReferral] = useState<Referral | null>(null);
  const [support, setSupport] = useState<Support | null>(null);
  const [busy, setBusy] = useState(true);
  useEffect(() => { let active = true; Promise.allSettled([tgfoxApi.referral(), tgfoxApi.support()]).then(([referralResult, supportResult]) => { if (!active) return; if (referralResult.status === "fulfilled") setReferral(referralResult.value); if (supportResult.status === "fulfilled") setSupport(supportResult.value); if ([referralResult, supportResult].some((result) => result.status === "rejected")) toast.error("Some account tools are temporarily unavailable. Available data is still shown."); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, []);
  const copy = (value: string) => navigator.clipboard.writeText(value).then(() => toast.success("Copied")).catch(() => toast.error("Copy is unavailable."));
  if (busy) return <div className="grid min-h-[360px] place-items-center"><div className="text-center"><LoaderCircle className="mx-auto animate-spin text-[#1769F5]" /><p className="mt-3 text-xs text-[#7F8A9A]">Loading account tools</p></div></div>;
  return <section className="panel-enter max-w-4xl"><h1 className="text-[22px] font-bold tracking-[-.03em]">Account tools</h1><p className="mt-1 text-xs text-[#8A93A4]">Referral growth and official TgFox support links. Seller activity has its own dedicated Sell Account page.</p><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="thin-card rounded-[24px] p-5"><p className="flex items-center gap-2 text-sm font-bold"><UsersRound size={17} className="text-[#1769F5]" /> Referral centre</p><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Friends referred" value={String(referral?.count || 0)} /><Metric label="Bonus earned" value={money(referral?.earnings || 0)} /></div>{referral?.link ? <div className="mt-4 flex items-center gap-2 rounded-2xl bg-[#F4F8FF] p-3"><p className="min-w-0 flex-1 truncate text-[10px] font-semibold text-[#52627D]">{referral.link}</p><button onClick={() => copy(referral.link)} className="pressable grid h-8 w-8 place-items-center rounded-lg bg-white text-[#1769F5]" aria-label="Copy referral link"><Copy size={15} /></button><button onClick={() => openTelegramLink(referral.link)} className="pressable grid h-8 w-8 place-items-center rounded-lg bg-white text-[#1769F5]" aria-label="Share referral link"><Share2 size={15} /></button></div> : <p className="mt-4 text-xs text-[#8A93A4]">Referral link is unavailable until the bot username is configured.</p>}</div><div className="thin-card rounded-[24px] p-5"><p className="flex items-center gap-2 text-sm font-bold"><Headphones size={17} className="text-[#1769F5]" /> Help & updates</p><p className="mt-2 text-[11px] leading-5 text-[#7D8798]">Use official TgFox channels for payment, order, and account support.</p><div className="mt-4 grid gap-2"><LinkButton label="Contact support" onClick={() => openTelegramLink(support?.support_link || support?.support_group || "")} /><LinkButton label="Open support group" onClick={() => openTelegramLink(support?.support_group || "")} /><LinkButton label="View updates" onClick={() => openTelegramLink(support?.updates_channel || "")} /></div></div></div></section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-[#F6F9FE] p-4"><p className="text-[9px] font-semibold text-[#8290A5]">{label.toUpperCase()}</p><p className="mt-2 text-lg font-bold">{value}</p></div>; }
function LinkButton({ label, onClick }: { label: string; onClick: () => void }) { return <button onClick={onClick} className="pressable flex items-center justify-between rounded-xl border border-[#E5EAF2] px-3 py-3 text-left text-xs font-semibold text-[#3B4658]"><span>{label}</span><span className="text-[#1769F5]">↗</span></button>; }
