/**
 * TgFox Wallet Gateway: white/blue financial overview that deliberately routes
 * users into separate deposit and withdrawal journeys using verified live data.
 */
import { useEffect, useRef, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, ChevronRight, LoaderCircle, RefreshCw, ShieldCheck, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { type Deposit, type WalletOverview, type Withdrawal, tgfoxApi } from "@/lib/api";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2 }).format(value || 0);
const stamp = (date?: string) => date ? new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(date)) : "—";

export function WalletWorkspace({ onOpenDeposit, onOpenWithdrawal }: { onOpenDeposit: () => void; onOpenWithdrawal: () => void }) {
  const [wallet, setWallet] = useState<WalletOverview | null>(null);
  const [deposits, setDeposits] = useState<Deposit[]>([]);
  const [withdrawals, setWithdrawals] = useState<Withdrawal[]>([]);
  const [busy, setBusy] = useState(true);
  const [summaryError, setSummaryError] = useState<string | null>(null);
  const mounted = useRef(true);

  const load = async (canUpdate: () => boolean = () => true) => {
    const [summaryResult, depositResult, withdrawalResult] = await Promise.allSettled([tgfoxApi.wallet(), tgfoxApi.deposits(), tgfoxApi.withdrawals()]);
    if (!canUpdate()) return;
    if (summaryResult.status === "rejected") {
      setSummaryError("Verified wallet data is temporarily unavailable. Your balance has not been changed.");
      return;
    }
    setWallet(summaryResult.value); setSummaryError(null);
    if (depositResult.status === "fulfilled") setDeposits(depositResult.value.items);
    if (withdrawalResult.status === "fulfilled") setWithdrawals(withdrawalResult.value.items);
    if ([depositResult, withdrawalResult].some((result) => result.status === "rejected")) toast.error("Some payment history is temporarily unavailable. Verified balance data is still shown.");
  };
  useEffect(() => {
    mounted.current = true;
    load(() => mounted.current).catch((error: Error) => { if (mounted.current) toast.error(error.message); }).finally(() => { if (mounted.current) setBusy(false); });
    return () => { mounted.current = false; };
  }, []);

  return <section className="panel-enter max-w-4xl"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.16em] text-[#1769F5]">WALLET CENTER</p><h1 className="mt-1 text-[23px] font-bold tracking-[-.04em] text-[#202633]">Move money without guesswork</h1><p className="mt-1 max-w-xl text-xs leading-5 text-[#7B8799]">Choose a dedicated flow for deposits or withdrawals. Every balance and history item comes from your verified account.</p></div><button onClick={() => { setBusy(true); load().catch((error: Error) => toast.error(error.message)).finally(() => setBusy(false)); }} aria-label="Refresh wallet" className="pressable grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[#E1E8F3] bg-white text-[#1769F5]"><RefreshCw size={16} /></button></div>
    {busy && !wallet ? <WalletSummaryLoading /> : null}{!busy && !wallet ? <WalletSummaryUnavailable message={summaryError} onRetry={() => { setBusy(true); load().catch((error: Error) => toast.error(error.message)).finally(() => setBusy(false)); }} /> : null}{wallet ? <><WalletSummary wallet={wallet} refreshing={busy} /><div className="mt-4 grid gap-4 md:grid-cols-2"><ActionCard tone="deposit" title="Add funds" text="Choose a live provider, create an instruction, and follow the exact payment details." meta={`From ${money(wallet.deposit_minimum)}`} action="Start secure deposit" icon={<ArrowDownLeft size={21} />} onClick={onOpenDeposit} /><ActionCard tone="withdraw" title="Withdraw USDT" text="Save the destination, review live fee estimates, and confirm before you request." meta={`From ${money(wallet.withdrawal.minimum)}`} action="Open withdrawal flow" icon={<ArrowUpRight size={21} />} onClick={onOpenWithdrawal} /></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><ActivityPanel title="Recent deposits" empty="No deposits yet." items={deposits.map((item) => ({ id: item.deposit_id, title: `${item.method || "Deposit"}${item.network ? ` · ${item.network}` : ""}`, amount: money(item.amount), status: item.status, at: item.created_at }))} /><ActivityPanel title="Recent withdrawals" empty="No withdrawal requests yet." items={withdrawals.map((item) => ({ id: item.withdrawal_id, title: `${item.network} withdrawal`, amount: money(item.net_amount || item.amount), status: item.status_label || item.status, at: item.created_at }))} /></div><div className="mt-4 flex gap-3 rounded-2xl border border-[#DCE8FA] bg-[#F6FAFF] p-4"><ShieldCheck size={19} className="mt-0.5 shrink-0 text-[#1769F5]" /><p className="text-xs leading-5 text-[#60728D]">For your safety, withdrawal requests use the address saved for the selected network. Deposit instructions are created only through enabled live providers. Never send funds outside the instructions shown inside this Mini App.</p></div></> : null}
  </section>;
}

function WalletSummary({ wallet, refreshing }: { wallet: WalletOverview; refreshing: boolean }) { return <div className="thin-card mt-4 overflow-hidden rounded-[24px] border border-[#C7DBFB] bg-[linear-gradient(135deg,#1769F5,#3C83F5_58%,#8AB9FF)] p-5 text-white shadow-[0_14px_32px_rgba(23,105,245,.16)]"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-[10px] font-bold tracking-[.14em] text-white/80"><WalletCards size={14} /> VERIFIED AVAILABLE BALANCE</p><p className="mt-3 text-4xl font-bold tabular-nums">{money(wallet.balance)}</p></div><div className="rounded-2xl border border-white/20 bg-white/15 px-3 py-2 text-right"><p className="text-[9px] font-bold tracking-wide text-white/75">SPENDABLE</p><p className="mt-1 text-sm font-bold">{money(wallet.net_spendable)}</p></div></div><div className="mt-5 flex items-center justify-between gap-3 border-t border-white/25 pt-4 text-xs"><p><span className="block text-white/75">Reserved</span><b className="mt-1 block">{money(wallet.reserved)}</b></p><p className="text-right"><span className="block text-white/75">Currency</span><b className="mt-1 block">{wallet.currency}</b></p></div>{refreshing ? <p className="mt-4 text-[10px] font-bold tracking-wide text-white/80">REFRESHING VERIFIED BALANCE</p> : null}</div>; }
function WalletSummaryLoading() { return <div className="thin-card mt-4 min-h-[188px] rounded-[24px] border border-[#DEE8F6] bg-white p-5"><div className="flex h-full min-h-[148px] flex-col justify-between"><div className="animate-pulse"><div className="h-3 w-40 rounded bg-[#E8EEF7]" /><div className="mt-5 h-10 w-44 rounded-xl bg-[#E8EEF7]" /></div><div className="grid grid-cols-2 gap-4 border-t border-[#EEF2F7] pt-4"><span className="h-8 rounded bg-[#F1F5FA]" /><span className="h-8 rounded bg-[#F1F5FA]" /></div></div></div>; }
function WalletSummaryUnavailable({ message, onRetry }: { message: string | null; onRetry: () => void }) { return <div className="thin-card mt-4 rounded-[24px] border border-[#D9E5F4] bg-white p-5 text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-2xl bg-[#EAF2FF] text-[#1769F5]"><WalletCards size={20} /></div><h2 className="mt-4 text-base font-bold text-[#263247]">Wallet summary is temporarily unavailable</h2><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-[#718096]">{message || "Please refresh to retrieve your verified wallet balance. No balance is estimated or shown while this data is unavailable."}</p><button onClick={onRetry} className="pressable mt-5 rounded-xl bg-[#1769F5] px-4 py-2.5 text-xs font-bold text-white">Retry wallet balance</button></div>; }

function ActionCard({ tone, title, text, meta, action, icon, onClick }: { tone: "deposit" | "withdraw"; title: string; text: string; meta: string; action: string; icon: React.ReactNode; onClick: () => void }) { const deposit = tone === "deposit"; return <div className={`thin-card overflow-hidden rounded-[24px] border ${deposit ? "border-[#C8DDFF]" : "border-[#E0E6EF]"}`}><div className={`p-5 ${deposit ? "bg-[#F4F8FF]" : "bg-[#F8FAFC]"}`}><div className="flex items-start justify-between gap-4"><div className={`grid h-11 w-11 place-items-center rounded-2xl ${deposit ? "bg-[#1769F5] text-white" : "bg-[#203E70] text-white"}`}>{icon}</div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${deposit ? "bg-[#E1EDFF] text-[#1769F5]" : "bg-[#EDF1F6] text-[#53657B]"}`}>{meta}</span></div><h2 className="mt-5 text-lg font-bold tracking-[-.03em] text-[#263247]">{title}</h2><p className="mt-2 min-h-[40px] text-xs leading-5 text-[#738096]">{text}</p></div><button onClick={onClick} className={`pressable flex h-12 w-full items-center justify-center gap-2 text-sm font-bold ${deposit ? "bg-[#1769F5] text-white" : "bg-[#203E70] text-white"}`}>{action}<ChevronRight size={17} /></button></div>; }
function ActivityPanel({ title, empty, items }: { title: string; empty: string; items: Array<{ id: string; title: string; amount: string; status: string; at: string }> }) { return <div className="thin-card rounded-[24px] p-5"><p className="text-sm font-bold text-[#263247]">{title}</p><div className="mt-3 divide-y divide-[#EBEFF5]">{items.slice(0, 3).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-xs font-bold text-[#344057]">{item.title}</p><p className="mt-1 text-[10px] text-[#8792A3]">{stamp(item.at)}</p></div><div className="text-right"><p className="text-xs font-bold text-[#273144]">{item.amount}</p><p className="mt-1 text-[10px] font-bold uppercase text-[#1769F5]">{item.status}</p></div></div>)}{!items.length ? <p className="py-7 text-center text-sm text-[#8792A3]">{empty}</p> : null}</div></div>; }
